@Emerald.Cheetah.Api_HostAddress = http://localhost:5298

GET {{Emerald.Cheetah.Api_HostAddress}}/weatherforecast/
Accept: application/json

DELETE https://localhost:7250/catalog/3

###
curl --request POST \
  --url https://dev-ovodle7wrwu14mdi.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{
    "client_id":"tDDmnfcHUNZrpF152nIBROcej0KEb1s9",
    "client_secret":"mFMvJ0oozAn6KJ2S396i9D1eXEeBDDu316IqsQObBz9e4D9He0qE7sWm_eb5QItt",
    "audience":"https://emerald-cheetah",
    "grant_type":"client_credentials"
  }'

curl --request DELETE \
  --url https://localhost:7250/catalog/3 \
  --header 'authorization: Bearer {PUT_YOUR_TOKEN_HERE}' 